lst = ["Apple","Guava","Mango","Banana","Kiwi"]
print("List length: ",len(lst))
print("First element "+str(lst[0]))
print("Last element "+str(lst[-1]))
lst.append("Papaya")
print("Updated List: "+str(lst))
lst.remove("Guava")
print("Updated List: "+str(lst))
lst.sort()
print("Updated List: "+str(lst))
lst.pop(1)
print("Updated List: "+str(lst))
lst.reverse()
print("Updated List: "+str(lst))
lst.clear()
print("Updated List: "+str(lst))
lst.insert(0,"Orange")
print("Updated List: "+str(lst))
lst.insert(0,"Tomato")
print("Updated List: "+str(lst))